etc/PrimarySourceDataModelSample.json, etc/PrimarySourceSetDataModelSample.json, etc/TeachingGuideDataModelSample.json
I was charged with
1. Replace `PrimarySourceSet:dplaer:timePeriod` with something from the period metadata schema
2. Replace `PrimarySource:dplaer:aggregation` with something else - possibly `schema:hasPart`?
3. Replace `TeachingGuide:dplaer:question` and `TeachingGuide:dplaer:activity` with a single field (`schema:text` or something better, like “body”). Expect that the field format will be markdown.  
4. Possibly replace `PrimarySource:text`, and `PrimarySourceSet:text` with something better, like “body”.  Expect that their field format will be markdown.
Resolving each:
1. Using `dct:temporal`, with the implication that the value is a `dct:PeriodOfTime`. I owe the Perio.do folks an email, and will get their opinion on applying that class to their `skos:Concept`s
2. Using …
=> Some initial revisions of the data model

provisioning/provision.yml
Building Ruby could/did(?) fail, because `make` was not installed. This
installs the dependencies for a Ruby build.
=> Add build-essentials to provisioned packages

Gemfile, app/controllers/guides_controller.rb, app/controllers/source_sets_controller.rb, app/controllers/sources_controller.rb, app/models/source_set.rb, config/initializers/friendly_id.rb, db/migrate/20150904190830_create_friendly_id_slugs.rb, db/migrate/20150904191008_source_sets_slug.rb, db/schema.rb, spec/controllers/guides_controller_spec.rb, spec/controllers/sources_controller_spec.rb, spec/models/source_set_spec.rb
This adds slugs to SourceSets with the [FriendlyId gem](https://github.com/norman/friendly_id).
The FriendlyId gem allows you to use human-readable ids in URLs, which is good for usability and SEO.  For example, instead of:
`http://dp.la/primary-source-sets/sets/82364`
you would get something like this:
`http://dp.la/primary-source-sets/sets/french-and-indian-war`
In this configuration, the name field for SourceSets is used to automatically generate the slug.
=> add set slugs with FriendlyId

Gemfile
This introduces versions for all gems.  It changes the dependency on `rails` from `4.1.6` to `~> 4.1.6`.  Whenever it does not conflict with the current `Gemfile.lock`, versions of gems match either the `heidrun` or `frontend` app.
=> tighen gem dependencies

.rspec, Gemfile, app/controllers/application_controller.rb, app/controllers/authors_controller.rb, app/models/admin.rb, app/views/layouts/application.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, config/settings.yml, db/migrate/20150904204928_devise_create_admins.rb, db/schema.rb, spec/controllers/authors_controller_spec.rb, spec/controllers/guides_controller_spec.rb, spec/controllers/source_sets_controller_spec.rb, spec/controllers/sources_controller_spec.rb, spec/factories/admins.rb, spec/helpers/application_helper_spec.rb, spec/models/author_spec.rb, spec/models/guide_spec.rb, spec/models/source_set_spec.rb, spec/models/source_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb, spec/support/controller_macros.rb, spec/support/database_cleaner.rb, spec/support/devise.rb, spec/support/shared_examples/admin_only_route.rb
This feature adds basic authorization to the app with the [Devise gem](https://github.com/plataformatec/devise).
Authentication is needed for this app so that admins (ie. DPLA staff) can log in to perform CRUD actions in the database.  After our initial launch in October, non-logged-in users will be able to view sets, sources, and guides; but until launch, only admins should have the ability to access any part of the application.  So for now, I added `before_action :authenticate_admin!` to the `ApplicationController`.  When we launch in October, this will need to change.
I kept most of the default Devise settings, expressed in the database migration, `config/initializers/devise.rb` and `config/locales/devise.en.yml`.  One exception is that I added the DPLA email address in [line …
=> authorization with devise gem

Gemfile
This removes one of the two identical statements in the `Gemfile` for the `devise` gem.  It reorganizes the file so that similar mistakes will be less likely in the future.  It also adds the `rubocop` gem.
=> clean up gemfile

app/helpers/application_helper.rb, app/views/authors/_form.html.erb, app/views/authors/edit.html.erb, app/views/authors/show.html.erb, app/views/guides/_form.html.erb, app/views/guides/edit.html.erb, app/views/guides/new.html.erb, app/views/guides/show.html.erb, app/views/source_sets/_form.html.erb, app/views/source_sets/edit.html.erb, app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb, app/views/sources/_form.html.erb, app/views/sources/edit.html.erb, app/views/sources/new.html.erb, app/views/sources/show.html.erb, spec/helpers/application_helper_spec.rb
This introduces markdown formatting to three new fields: `source_set.name`, `source.name`, and `guide.name`.
These three markdown fields differ from the previous markdown fields in that they need to be rendered as inline HTML elements.  Since `Redcarpet` by default encloses all markdown in `<p>` tags, I made a new helper method, `inline_markdown`.  Most of the changes to the views are simply using this new method to render `source_set.name`, `source.name`, and `guide.name`.
In addition, I added instructional text to the `source_set`, `guide`, and `source` input forms, and fixed a few typos.
This addresses [#7985](https://issues.dp.la/issues/7985)
=> add markdown fields

app/controllers/sources_controller.rb, app/views/sources/_form.html.erb, app/views/sources/show.html.erb, db/migrate/20150911134246_add_citation_credits_to_sources.rb, db/migrate/20150911134545_sources_citation_credits_text_limits.rb, db/schema.rb, spec/factories/sources.rb
This introduces the ability to persists source citations and credit in the database, and enter them via the admin web interface.
It is important to persist these (rather than generating them dynamically through the API) because if an item disappears from the DPLA library, we need to be able to retain citation and credit information.  
This addresses [#7991](https://issues.dp.la/issues/7991)
=> Add credits, citation to sources

spec/spec_helper.rb, spec/views/authors/index.html.erb_spec.rb, spec/views/authors/show.html.erb_spec.rb, spec/views/guides/show.html.erb_spec.rb, spec/views/source_sets/index.html.erb_spec.rb, spec/views/source_sets/show.html.erb_spec.rb, spec/views/sources/show.html.erb_spec.rb
This fixes view specs, which were failing.  We didn't detect that they were failing because they were not loading with the rest of the tests when running `rspec`.
To get the view specs to pass, I changed `require spec_helper` to `require rails_helper`.  This change was made to the rest of the specs in PR#16, but I had overlooked the views specs. 
To get the view specs to load, I added a statement to `spec_helper`.
=> load view specs and require rails_helper

Gemfile, etc/PrimarySourceDataModelSample.json, etc/PrimarySourceSetDataModelSample.json, spec/lint_samples_spec.rb
This adds citation and provenance metadata to the `Source` class, and adds more detailed temporal metadata.  These changes are motivated by conversations I've had with FA.
Although the citation and provenance metadata is accessible by linking to the ore:Aggregation, we want to include it here so that if the ore:Aggregation disappears, as they sometimes do, we can retain the information here.
FA has decided that for the primary source sets time periods, she is going to use the [US History Content Standards eras](http://www.nchs.ucla.edu/history-standards/us-history-content-standards). Since we now have time periods with start and end dates, I took a stab at representing them using DC's PeriodOfTime class. 
A particular concern is this: As far as I know, the US History Content Standards do …
=> temporal, citation, and provenance

README.md, lib/tasks/primary_source_sets.rake
This introduces a rake task that creates a sample admin account for use in testing and development.
=> add rake task to create sample admin account

app/views/source_sets/_form.html.erb, app/views/source_sets/show.html.erb, app/views/sources/_form.html.erb, app/views/sources/show.html.erb, db/migrate/20150929184236_sources_text_limits2.rb, db/schema.rb
This introduces some small edits to data entry fields and forms based on feedback from FA.  It addresses [#8055](https://issues.dp.la/issues/8055).
Field change:
* Increase the text limit for `guide.textual_content` from 65535 (MySQL TEXT) to 16777215 (MySQL MEDIUMTEXT)
Form changes:
* Change form label for `source_set.description` to "SEO description".
* Change form label for `source.name` to "Caption".
* Change form label for `source.textual_content` to "Description / transcription".
This also deletes a table definition from `db/schema.rb` that was mistakenly introduced in a previous PR.
=> edit data entry fields and forms

app/helpers/application_helper.rb, app/models/source.rb, app/views/sources/show.html.erb, spec/helpers/application_helper_spec.rb
This adds a `frontend_path`, that constructs a link to the frontend.  It checks for the correct `/` between the path base defined in `Settings.frontend.url` and the appended path name.  This is more fool-proof than the previous code, which was unforgiving if both the path base and the appended path name did not have `/`s in the right places.  
It also moves the method out of the `source` model, to a more appropriate location in a `helper`.
This should fix the current problem on staging, where the path is showing up without the adjoining `/` (see [#8062](https://issues.dp.la/issues/8062))
=> add frontend_path method

app/controllers/videos_controller.rb
This fixes a bug whereby I'd forgotten to update `VideosController#notifidcations_url` with the necessary concatenation of some new settings variables.
=> Fix bug in video notification URL

app/controllers/application_controller.rb, config/settings.yml, spec/controllers/application_controller_spec.rb
Add handling for Zencoder named credential sets.  These are named sets of Amazon IAM (access management) keys that can be used in order to have separate permissions on development, staging, and production buckets.
=> Add Zencoder named credentials

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
A Zencoder credential name has to be added to each element of the `outputs` property of the job request, in addition to the top-level object, where it exists now.
=> Add Zencoder named credentials to outputs

app/views/audios/edit.html.erb, app/views/audios/index.html.erb, app/views/audios/show.html.erb, app/views/sources/show.html.erb, app/views/videos/edit.html.erb, app/views/videos/index.html.erb, app/views/videos/show.html.erb, spec/controllers/audios_controller_spec.rb, spec/controllers/videos_controller_spec.rb
This removes `audio` and `video` `edit` views and link to those views.  It addresses ticket [#8071](https://issues.dp.la/issues/8071).
=> remove a/v edit views

app/assets/javascripts/docupload.js, app/assets/javascripts/imgupload.js, app/controllers/documents_controller.rb, app/controllers/images_controller.rb, lib/primary-source-sets/pss_browser_uploads.rb
Fix upload forms so that the Content-Type field assigned.  Amazon S3 defaults to "application/octet-stream" if it is not, and this causes PDFs to download instead of being displayed in the browser.  It also causes other files to be uploaded as octet-stream, but it's less noticable than with PDFs.
Also improve the frontend upload event-handler code to check that a file has been chosen.
=> Fix Content-Type of uploaded images and documents

app/views/layouts/application.html.erb, config/initializers/assets.rb
Add a favicon, taken from frontend-assets.
This is related to [PR#3 on frontend-assets](https://github.com/dpla/frontend-assets/pull/3).
This addresses [task #8070](https://issues.dp.la/issues/8070).
=> get favicon from frontend-assets

app/views/layouts/application.html.erb, config/initializers/assets.rb
Reverts dpla/primary-source-sets#45
Turns out this is un-necessary b/c `primary-source-sets` is already showing a favicon courtesy of the frontend when deployed on staging and production.
=> Revert "get favicon from frontend-assets"

app/models/source.rb
Have a deletion of a Source record cause a deletion of the corresponding Attachment record.
=> Fix Source has_many relationship with Attachment

app/views/source_sets/show.html.erb
This fixes the attribute name of the featured image on the `source_sets#show` view.  The error was preventing the page from rendering.
This addresses [ticket #8079](https://issues.dp.la/issues/8079).
=> fix featured image attr name

app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb, spec/views/source_sets/index.html.erb_spec.rb
On `sets#show` order `sources` by their created date (earliest created should appear first).
On `sets#index`, order `sets` by their created date (earliest created should appear first).
This addresses [ticket #8078](https://issues.dp.la/issues/8078)
=> order sources and sets by created_at

.travis.yml, Gemfile, Vagrantfile, app/assets/javascripts/avupload.js, app/assets/javascripts/docupload.js, app/assets/javascripts/imgupload.js, app/assets/javascripts/upload.js, app/views/audios/new.html.erb, app/views/shared/_s3form.erb, app/views/videos/new.html.erb, config/initializers/assets.rb, provisioning/provision.yml, spec/javascripts/av_upload_handler_spec.js, spec/javascripts/doc_upload_handler_spec.js, spec/javascripts/helpers/jasmine-query.js, spec/javascripts/image_upload_handler_spec.js, spec/javascripts/support/jasmine.yml, spec/javascripts/support/jasmine_helper.rb, spec/javascripts/upload_handler_spec.js
Addresses https://issues.dp.la/issues/8075
* Refactor upload-related Javascript, creating UploadHandler, AVUploadHandler, DocUploadHandler, and ImageUploadHandler functions, reducing redundancy and allowing unit testing.
* Add `id` attribute to upload forms so that they are distinguishable from search forms that were recently added to the layout.
* Add Jasmine tests for Javascript code.
* Update Vagrantfile so that you can view Jasmine tests on http://localhost:3001/
=> Refactor Javascript and add tests

app/views/guides/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_analytics.html.erb, app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb, config/settings.yml
Add Google Analytics tracking code.
It's enabled by setting `googleanalytics.tracker` in `settings.local.yml` to a string value.
I've only added it to the views for `/sources/:id` and `/sets/:id` because I'm not sure which ones are public, versus administrative.
@AudreyAltman, can you tell me what pages should be tracked, or at least help me identify which ones are eventually going to be public?  I'm not clear on this because of the presence of certain links that look like they should only be on admin pages.  It does appear that `/` (`source_sets#index`) would be another candidate.
=> Add Google Analytics

app/models/audio.rb, app/models/document.rb, app/models/image.rb, app/models/video.rb
This adds a destroy dependency to the assets-attachments relationship so that when an asset is deleted, its rows in the attachments table are also deleted.
=> add destroy depenedency to assets-attachments reltionship

Gemfile, app/assets/stylesheets/application.css, app/views/images/show.html.erb, app/views/sources/_image.html.erb, app/views/sources/show.html.erb, config/initializers/assets.rb
Add Lightbox2 image viewer
The viewer displays large images in the public `/sources:id` (show source) page and prevents convenient right-click downloads.  It displays images in what I assume will be the admin-only `/images:id` page, without preventing right-click-downloads.
=> Add image viewer

app/assets/stylesheets/primary_source_sets.css, app/helpers/application_helper.rb, app/models/source.rb, app/views/layouts/application.html.erb, app/views/source_sets/_source_list.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb, spec/helpers/application_helper_spec.rb, spec/models/source_spec.rb
This introduces CSS styling for `source_sets#show`.  It includes one helper method for concatenating multiple authors and their affiliations.  It also includes two new methods in the `Source` model to ease access to image assets of specified sizes.  Finally, it corrects a small HTML error in `sources#show`.
=> style source_sets#show

app/assets/stylesheets/primary_source_sets.css, app/controllers/guides_controller.rb, app/controllers/source_sets_controller.rb, app/controllers/sources_controller.rb, app/views/layouts/application.html.erb
Add breadcrumb navigation to public-facing pages:  source sets, sources, and guides.
Do we need a link to the home page of the main site?
=> Add breadcrumbs

app/assets/javascripts/application.js, app/views/sources/_image.html.erb
This gets rid of the context menu (right click menu) of Lightbox's links to big images.  We had previously removed the ability to right-click and "download image as" but this gets rid of the menu with the options to open the link in another window or "save link as."
=> Disable context menu on lightbox links to big images

app/controllers/application_controller.rb, app/controllers/audio_notifications_controller.rb, app/controllers/audios_controller.rb, app/controllers/authors_controller.rb, app/controllers/documents_controller.rb, app/controllers/guides_controller.rb, app/controllers/images_controller.rb, app/controllers/source_sets_controller.rb, app/controllers/sources_controller.rb, app/controllers/video_notifications_controller.rb, app/controllers/videos_controller.rb, app/views/guides/show.html.erb, app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb, spec/controllers/guides_controller_spec.rb, spec/controllers/source_sets_controller_spec.rb, spec/controllers/sources_controller_spec.rb, spec/support/devise.rb
Allow public access to `source_set#index`, `source_sets#show`, `source#show`, and `guide#show`.  Only show admin menus and information on these views if the admin is logged in.
This addresses task [#8085](https://issues.dp.la/issues/8085).
=> allow public access to some views

app/assets/javascripts/style.js, app/assets/stylesheets/primary_source_sets.css, app/views/guides/show.html.erb, app/views/layouts/application.html.erb, app/views/source_sets/_source_list.html.erb, app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb
This makes many small style and static content fixes for the public-facing pages.  They include:
`sets#index`
* Fix email link in introductory text
* Remove comma after “These sets were created”
* Add paragraph break before “These sets were created" 
* Render markdown for set titles
* Hyperlink thumbnails
* Remove breadcrumbs
`set#show`
* Hyperlink thumbnails 
* Left-align source titles
* Change source tile background color from light blue to light grey
* Make the blue title bar and the grey "Teaching Guide" sidebar the same height (this is done with JavaScript, which will not fix the style on browsers with JavaScript disabled)
`source#show`
* Add `/item` to "Need more information..." URLs
* Remove “Send feedback” div from bottom of page
`guide#show`
* Remove author name and affiliation …
=> style and static content fixes for public faces pages

app/controllers/guides_controller.rb, app/controllers/source_sets_controller.rb, app/controllers/sources_controller.rb, app/helpers/application_helper.rb, app/helpers/markdown_helper.rb
This renders markdown in the breadcrumbs.  It addresses [#8087](https://issues.dp.la/issues/8087).
=> render markdown in breadcrumbs

app/views/guides/show.html.erb, app/views/layouts/application.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb
Move breadcrumb link rendering to just those three views that need it, taking it out of the application layout.
The presence of a `url_for` call that asked for the location of `source_sets#index` caused a server error in the context of a Devise login page, with an error indicating that no route matches `{:action=>"index", :controller=>"devise/source_sets"}`.
=> Fix sign-in page server error

app/assets/javascripts/style.js, app/assets/stylesheets/primary_source_sets.css, app/views/guides/show.html.erb, app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb
This makes some presentational adjustments to the public UI for launch.  Changes include:
`source_sets#index`
* Remove paragraph break in intro text
* Remove period at end of byline
* Fix width of set tiles for mobile view
* Make bottom margin of first aside module smaller
`source_sets#show`
* Eliminate text wrapping in intro text
`guides#show`
* Make title bar and first `aside` module the same height (this is done dynamically with JavaScript, which is not ideal but will get us to launch)
* Remove period at end of byline
* Make bottom margin of first aside module smaller
=> UI presentational fixes for launch

Gemfile, lib/tasks/primary_source_sets.rake
Add the `turnout` gem for putting the app into "maintenance mode."
Maintenance mode is achieved by placing a file named `maintenance.yml` in the app's `tmp` directory.  For example:
```
---
reason: We're performing some backend maintenance; back in a minute!
response_code: 503
retry_after: 60
```
=> Add turnout for maintenance messages

app/assets/stylesheets/primary_source_sets.css
This sets a default height and width of `textarea` elements to ease data entry.  It addresses [ticket #8135](https://issues.dp.la/issues/8135).
=> set height and width for textareas

app/views/guides/show.html.erb, app/views/layouts/application.html.erb, app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb
This adds unique SEO tags to the `head` of public-facing views.
1. A `title` tag.
2. A `meta` `description` tag.
3. A `canonical` `link` tag, which should be an absolute URL with a trailing slash.  `source_set#index` does not have a `canonical` `link` tag because in future iterations, the contents of this page will change based on search parameters (ie. there will not be only one version of the page).
The contents of these tags are text-only, so they are stripped of any nested HTML tags where appropriate.
=> title, description, & canonical link tags

app/assets/javascripts/style.js, app/assets/stylesheets/primary_source_sets.css, app/views/guides/show.html.erb
This makes some small changes to the style of the `guide`.
It removes the blue background from the title and byline, instead making the title blue text on a white background.  It also adds more whitespace in-between sections of the main content of the page.
This addresses [ticket #8150](https://issues.dp.la/issues/8150).
=> fix title style and content spacing

app/models/source.rb, spec/factories/attachments.rb, spec/models/source_spec.rb
This ensures that `Source#assets` does not return any `nil` values.  `nil` values may occur if someone deletes an asset (an `Image`, `Document`, `Video`, or `Audio`) without deleting its association to a `Source`, as expressed in the `attachments` table.  There are validations in place to dependent-destroy these associations, but this in an extra precaution that will catch any mistakes that have occurred or could occur in the future.
This addresses [task #8167](https://issues.dp.la/issues/8167).
=> do not return nil assets in Source#assets

app/views/shared/_top_nav.html.erb
Change the DPLAfest link in the top menu to `http://dp.la/info/get-involved/dplafest/april-2016/`.  This addresses [ticket #8183](https://issues.dp.la/issues/8183).
=> change dplafest link

app/assets/stylesheets/primary_source_sets.css
Reduce the whitespace on `guides`, below the byline and above the `.textual-content` block.  This addresses [note #6 in task #8150](https://issues.dp.la/issues/8150#note-6).  I tested it locally, and also showed it Franky for approval.
=> reduce whitespace below guide byline

app/views/guides/_form.html.erb, app/views/source_sets/_form.html.erb, app/views/sources/_form.html.erb
This adds "submit" buttons to the tops of data entry forms for `source_sets`, `guides`, and `sources`.  When tested locally, these buttons work as expected.
This addresses [ticket #8101](https://issues.dp.la/issues/8101).
=> add save button to top of set, source, and guide forms

app/controllers/source_sets_controller.rb, app/models/source_set.rb, app/views/source_sets/_form.html.erb, app/views/source_sets/_set_list.html.erb, app/views/source_sets/index.html.erb, spec/controllers/source_sets_controller_spec.rb, spec/models/source_set_spec.rb, spec/views/source_sets/index.html.erb_spec.rb
This allows admins to assert whether or not `source_sets` are "published".  Published sets are visible to all users from `source_sets#index`; unpublished sets are visible only to admins.  The `source_sets` table has a column, `published`, that takes a boolean value.  Up to this point, the default has been to set all `source_sets` as `published=true` in the database.
Changes include:
* A place on the `source_sets` form to specify whether a set is "published" or not.
* Model methods that get published and unpublished sets from the database.
* Setting instance variables in the `source_sets#index` controller for `@published_sets` and `@unpublished_sets`.
* Abstracting out a view partial that renders a list of sets, be they published or unpublished.
* Changing the `source_sets#index` view to …
=> Allow admins to designate and view unpublished sets

spec/javascripts/av_upload_handler_spec.js, spec/javascripts/doc_upload_handler_spec.js, spec/javascripts/image_upload_handler_spec.js, spec/javascripts/upload_handler_spec.js
This cleans up the use of global and Fixture variables and in the jasmine tests.
In this app, some JavaScript variables are set in views (ie. `pss_asset_type`).  Before, these variables were simulated in Jasmine tests by adding them to Fixtures with HTML `<script>` tags.  For example:
<script>var pss_asset_type = "video";</script>
While this accurately replicates the way in which these variables are set the app, the difficulty with this approach is that when Jasmine runs its `cleanUp` function between tests, the JavaScript variables are not cleaned up, so they remain set for _all_ subsequent tests.
This introduces a different approach.  The variables set in views are introduced as global variables for the Jasmine tests .  Since they are global variables, they can be set in Before blocks, …
=> clean up global variables

app/assets/javascripts/avupload.js, app/assets/javascripts/docupload.js, app/assets/javascripts/imgupload.js, app/assets/javascripts/upload.js, app/controllers/audios_controller.rb, app/controllers/documents_controller.rb, app/controllers/images_controller.rb, app/controllers/videos_controller.rb, app/views/audios/new.html.erb, app/views/documents/new.html.erb, app/views/images/new.html.erb, app/views/sources/show.html.erb, app/views/videos/new.html.erb, spec/controllers/audios_controller_spec.rb, spec/controllers/documents_controller_spec.rb, spec/controllers/images_controller_spec.rb, spec/controllers/videos_controller_spec.rb, spec/javascripts/av_upload_handler_spec.js, spec/javascripts/doc_upload_handler_spec.js, spec/javascripts/image_upload_handler_spec.js, spec/javascripts/upload_handler_spec.js, spec/support/shared_examples/media_controller.rb
This allows creation of media assets (`image`, `document`, `video`, or `audio`) with a specified `source`. 
Sources and assets have a many-to-many relationship in the database.  Previously, admins could only persist relationships between assets and sources using the form on the `sources#new` view to select existing assets from a menu. This made workflow difficult for admins.
This PR introduces a way to specify which source an asset is associated with upon the asset's creation.  A source can be specified in a `source_id` parameter in the asset's `#new` route.  When the asset is saved, its association with the source is saved as well.
And important particularity of this approach is that _upon creation_, an asset can only be associated with one source (there are other ways to build …
=> Allow creation of media assets with specified source.

app/controllers/source_sets_controller.rb, app/models/source_set.rb, app/views/source_sets/_form.html.erb, app/views/source_sets/show.html.erb, db/migrate/20151221141547_add_year_to_source_set.rb, db/schema.rb, spec/factories/source_sets.rb, spec/models/source_set_spec.rb
This persists a `year` attribute for `source_sets`.  It adds a column to the `source_sets` table.  The model validates that `year` is an integer.  It provides an interface for admins to add, view, and edit the `year`.  
This addresses [ticket #8204](https://issues.dp.la/issues/8204).
=> persist year attribute for source_sets

db/migrate/20151221210743_publish_existing_sets.rb, db/schema.rb
This sets the value of the `published` attribute for all existing `source_sets` to `true`.  We are about to deploy code to the production server that adds the `published` column to the `source_sets` table.  In order to ensure that all existing `source_sets` in production remain visible to the end user, we need to publish them all (unpublished sets are hidden from the end user).  This could be done from the rails console in the production server, but doing it as a migration will prevent both human error and "downtime" for the sets.
I tested this locally and it executed as expected.
=> publish all existing sets

app/assets/stylesheets/primary_source_sets.css, app/views/authors/_form.html.erb, app/views/guides/_form.html.erb, app/views/images/new.html.erb, app/views/source_sets/_form.html.erb, app/views/sources/_form.html.erb, app/views/tags/_form.html.erb, app/views/vocabularies/_form.html.erb
This adds a little style to the admin input forms to make page elements more visible, thus making data entry easier.  I added a class name to the admin forms so that they can be distinguished from other forms on the pages, such as the DPLA search box.
This also corrects an oversight in the `tag` and `vocabulary` forms - to be consistent with the other admin forms in the application, they needed "Submit" buttons at the top of the form, as well as the bottom.
I have run the views locally and confirmed that they look as expected.
This addresses [ticket #8206](https://issues.dp.la/issues/8206).
=> style form inputs and text areas

spec/models/audio_spec.rb, spec/models/document_spec.rb, spec/models/image_spec.rb, spec/models/video_spec.rb, spec/support/shared_examples/media_asset.rb
This fixes the specs for media assets regarding validations in the models.  With this change, all of our rspec tests are passing, and none are skipped!
This addresses [ticket #8193](https://issues.dp.la/issues/8193).
=> fix validation specs for media assets

app/helpers/application_helper.rb, app/models/source.rb, app/views/audios/new.html.erb, app/views/audios/show.html.erb, app/views/documents/new.html.erb, app/views/documents/show.html.erb, app/views/images/new.html.erb, app/views/images/show.html.erb, app/views/source_sets/_source_list.html.erb, app/views/sources/show.html.erb, app/views/videos/new.html.erb, app/views/videos/show.html.erb, spec/models/source_spec.rb
This moves a helper method into a model.  The helper method was `source_name`.  It returned a `source`'s `name` if present; if not, it returned its `aggregation`.  This functionality makes more sense as an instance method of the `Source` model, so I moved it, renamed it `display_name`, and wrote a test.  I also changed the associated views and checked them all locally.
This addresses [ticket #8202](https://issues.dp.la/issues/8202).
=> move source_name helper to source model

app/helpers/application_helper.rb, app/models/concerns/authored.rb, app/models/guide.rb, app/models/source_set.rb, app/views/guides/show.html.erb, app/views/source_sets/show.html.erb, spec/helpers/application_helper_spec.rb, spec/models/guide_spec.rb, spec/models/source_set_spec.rb, spec/support/shared_examples/authored.rb
This refactors existing code by introducing a concern module for models with associated authors.  Functionality is factored out of the `ApplicationHelper` and the `Source` and `Guide` models.
This addresses [ticket #8202](https://issues.dp.la/issues/8202).
=> move author list from helper to model concern

.travis.yml, spec/spec_helper.rb
The Travis configuration was using the wrong CodeClimate token, and the CodeClimate test reporter was not being started.
=> Set up and run CodeClimate to check code coverage

app/helpers/markdown_helper.rb, app/views/guides/show.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb
Remove the double-HTML-encoding of characters into HTML entities.
See https://issues.dp.la/issues/8199
The `#inline_markdown` method call is not necessary for `<title>` elements, because it's not desirable to have markup in titles -- all we need is straight text.  The `#inline_markdown` method encodes HTML entities, and the resulting string was being encoded one more time by Rails automatically when the view was rendered.
=> Fix double-encoding of characters in titles

app/assets/javascripts/style.js, app/assets/stylesheets/primary_source_sets.css, app/controllers/source_sets_controller.rb, app/models/source_set.rb, app/views/source_sets/_set_list.html.erb, app/views/source_sets/index.html.erb, config/settings.yml, spec/controllers/source_sets_controller_spec.rb, spec/models/source_set_spec.rb
This adds functionality to show `tags` on the user interface, and allows users to filter by `tags`.  `tags` only appear on the the `source_sets#index` view.
Basic CRUD interfaces for tags were added in [PR#84](https://github.com/dpla/primary-source-sets/pull/84); however, tags were _only_ visible to logged-in admins.  This PR introduces functionality available to non-logged-in users.
Here is an example of the how the functionality should work:
A user goes to `/primary-source-sets/sets?tags[]=dogs` and sees only those sets with a tag whose label is `dogs`.  All of the tags associated with a set (including `dogs`) are listed beneath each set.
One set also has a tag `cats`.  The user clicks on `cats`, and is taken to `/primary-source-sets/sets?tags[]=dogs&tags[]=cats`.  The users is shown …
=> show and filter by tags on user interface

app/assets/javascripts/results-bar.js, app/assets/stylesheets/primary_source_sets.css, app/controllers/source_sets_controller.rb, app/helpers/source_sets_helper.rb, app/models/source_set.rb, app/views/source_sets/index.html.erb, config/initializers/assets.rb, spec/controllers/source_sets_controller_spec.rb, spec/helpers/source_sets_helper_spec.rb, spec/javascripts/support/jasmine.yml, spec/models/source_set_spec.rb
This introduces a feature that allows users to sort sets by `created_date` and `year` on the `sets#index` view.  
The sort option is included in the URI as an `order` param.  For example: `/sets?order=recently_added'`  The application recognizes three legitimate `order` params, `recently_added`, `chronology_asc`, and `chronology_desc`.  Any other `order` param is ignored.  If there is no legitimate `order` param, it defaults to `recently_added`.
Changes include:
* A method in the `SourceSet` model that parses the `order` param and adds sort options to a database query.
* Updating the `source_sets#index` controller method.
* Adding a dropdown menu to the view so users can select a sort option.
* Unobtrusive JavaScript.  If JavaScript is disabled, a form submit button will appear.  If …
=> order sets by date created or year

app/assets/javascripts/application.js, app/assets/javascripts/nav-menu-effects.js, app/assets/stylesheets/vendor/main.css.erb, app/views/layouts/application.html.erb, app/views/shared/_header.html.erb
Fixes https://issues.dp.la/issues/8093
* Add "viewport" `<meta>` element to the layout that makes mobile browsers show the page at the correct scale.
* Add a "charset" `<meta>` element while we're at it, as a best practice.
* Enable the menu buttons that show the navigation menu when the screen is small.
It would be nice not to need code to pull off the menus. I've implemented an adaptive menu like this (with the menu that gets replaced by a button) in pure CSS, not that I understand it that well. We can probably get rid of some of the code in a future iteration. It's harder to do it differently now without rewriting a lot of stylesheets and templates.
=> Fix mobile layout and menus

app/views/source_sets/_set_list.html.erb, app/views/source_sets/index.html.erb, config/settings.yml
This solves two bugs that that were introduced in release v1.2.2.  
1. In v1.2.2, user-selected tags and orders are over-riding one another. For example, from the browser window, if I select a tag and then select and order, I will lose the tag definition in the URI, and visa versa. This ensures that when tags are selected/deselected, and when orders are changed, all relevant params are passed along.
2. It changes default value of `display_tags_on_public_ui` to `false`.
=> fix settings file and muliple tags/orders params

app/helpers/source_sets_helper.rb
In the "Sort by" menu, change the word "Chronologially" to "Chronology" wherever it occurs, as per request from Franky.  This addresses ticket [#8233](https://issues.dp.la/issues/8233).
=> change sort by menu language

app/assets/stylesheets/primary_source_sets.css, app/controllers/source_sets_controller.rb, app/controllers/vocabularies_controller.rb, app/helpers/source_sets_helper.rb, app/models/source_set.rb, app/models/vocabulary.rb, app/views/source_sets/_no_results.html.erb, app/views/source_sets/_set_list.html.erb, app/views/source_sets/index.html.erb, app/views/vocabularies/_form.html.erb, app/views/vocabularies/show.html.erb, db/migrate/20151222204207_remove_height_and_width_from_images.rb, db/migrate/20160114144803_add_filter_to_vocabulary.rb, db/schema.rb, spec/controllers/source_sets_controller_spec.rb, spec/factories/vocabularies.rb, spec/helpers/source_sets_helper_spec.rb, spec/models/source_set_spec.rb, spec/models/vocabulary_spec.rb
This introduces a feature that allows public users to filter source sets by tags on the `source_sets#index` view.
There are two ways to filter - dropdown menus, and clicking on a linked tag listed under a set.
Changes to the code include:
* In the `source_sets#index` controller, the instance variable `@tags` used to be an Array of tag slugs, taken from `params[:tags]`.  However, the view need access to the entire Tag model, not just the slugs.  So, the value of `@tags` is now an Array of `Tag`s.
* There is a new boolean data field for `vocabularies` called `filter`.  This field allows the admin to determine whether or not a vocabulary will be filterable on public UI. It will help admin workflows, b/c they can ensure that all necessary data is in the database before “turning on” the …
=> vocab-sensitive tag filtering

app/assets/stylesheets/primary_source_sets.css, app/views/source_sets/index.html.erb
On the `source_sets#index view`, link the "Primary Source Sets" header to `source_sets#index` without any order/filter parameters. This will serve as an "out" for users who become confused by the order/filter options. 
This feature was requested by Franky.  It addresses [ticket #8242](https://issues.dp.la/issues/8242).
=> link Primary Source Sets header

README.md, Vagrantfile, app/controllers/confirmations_controller.rb, app/controllers/registrations_controller.rb, app/models/admin.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/confirmations/show.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/registrations/edit.html.erb, app/views/registrations/index.html.erb, app/views/registrations/new.html.erb, app/views/shared/_admin_menu.html.erb, config/environments/development.rb, config/environments/production.rb, config/initializers/devise.rb, config/routes.rb, config/settings.yml, db/migrate/20160113221031_add_confirmable_to_admin.rb, db/schema.rb, spec/controllers/registrations_controller_spec.rb, spec/factories/admins.rb, spec/models/admin_spec.rb, spec/support/shared_examples/basic_controller.rb
Add account management, mostly using Devise, and overriding some of its default behavior.
Accounts are only created by admins. When the account is created, an email is sent to the new account's address for confirmation. During confirmation, the new user must set a password.
README.md contains some notes about setting up `mailcatcher` for development with confirmation emails.
References https://issues.dp.la/issues/8162
Possible TODO:  Add a full-name field to Admin.
=> Add account management

app/assets/stylesheets/primary_source_sets.css
This fixes a CSS mistake introduced in PR#107.  The mistake caused the `h1` element on `source_sets#index`, "Primary Source Sets", to be orange instead of blue.  This was due to a declaration elsewhere in the CSS making all `a` elements orange.  Changing the declaration here from `a:link` to `a` ensures that `h1` will be blue.  This branch has been deployed to staging.
=> fix anchor style

Gemfile, app/assets/stylesheets/primary_source_sets.css, app/controllers/application_controller.rb, app/controllers/guides_controller.rb, app/controllers/registrations_controller.rb, app/controllers/source_sets_controller.rb, app/controllers/sources_controller.rb, app/models/admin.rb, app/policies/access_policy.rb, app/views/devise/sessions/new.html.erb, app/views/registrations/edit.html.erb, app/views/shared/_admin_menu.html.erb, db/migrate/20160119215143_add_status_to_admin.rb, db/schema.rb, spec/controllers/guides_controller_spec.rb, spec/controllers/registrations_controller_spec.rb, spec/controllers/source_sets_controller_spec.rb, spec/controllers/sources_controller_spec.rb, spec/factories/admins.rb, spec/factories/guides.rb, spec/factories/source_sets.rb, spec/factories/sources.rb, spec/models/admin_spec.rb, spec/support/controller_macros.rb, spec/support/shared_examples/admin_only_route.rb, spec/support/shared_examples/anon_user_redirects.rb, spec/support/shared_examples/nested_controller.rb, spec/support/shared_examples/redirecting_controller.rb
Add a permissions system, with administrator roles.
See https://issues.dp.la/issues/8163
The specification was to add a class of view-only users (who can view unpublished sets, but not modify or create them), and a permissions system is necessary to achieve this.
=> Add permissions system

config/settings.yml
This removes an obsolete setting from `Settings.yml`.  
This setting helped us to transition to tagging system without in coordination with admins' workflow.  It was used to hide tags from the public until admins had entered all the tag data into the database.  Since then, we have added functionality that allows admins to control which tags are displayed to public users.  All uses of the `display_tags_on_public_ui` setting were removed in [PR#105](https://github.com/dpla/primary-source-sets/pull/105).
This addresses [ticket #8246](https://issues.dp.la/issues/8246).
It relates to [automation PR#147](https://github.com/dpla/automation/pull/147) and [aws PR#35](https://github.com/dpla/aws/pull/35/files).
=> remove obsolete tag setting

app/views/guides/show.html.erb, app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb, spec/views/guides/show.html.erb_spec.rb, spec/views/source_sets/index.html.erb_spec.rb, spec/views/source_sets/show.html.erb_spec.rb, spec/views/sources/show.html.erb_spec.rb
This introduces views specific to reviewers.  Reviewers are a class of admins who need to see unpublished sets (and their associated sources and guides), but do not need access to edit/delete functions. This filters out links to these pages on set, source, and guide views for reviewers.
Note that reviewers already cannot access edit or delete routes, and if they try they will be redirected to more benign pages. But to avoid confusion, it would be best if link to edit/delete pages didn't appear to reviewers at all.  
There are also a couple small changes to the views to clarify information for reviewers, who do not have intimate knowledge of current workflows.
Finally, this adds tests for manager, editor, and reviewer admins for the associated views.
This addresses [ticket …
=> views for reviewers

README.md, lib/tasks/primary_source_sets.rake
This updates the README file with instructions for creating an initial admin account with manager-level permissions.  It removes a rake task that no longer works with the new, more advanced account management features. 
This addresses [ticket #8298](https://issues.dp.la/issues/8298).
=> update instructions to create initial admin account

app/assets/javascripts/carousel.js, app/assets/javascripts/style.js, app/assets/stylesheets/primary_source_sets.css, app/models/source.rb, app/views/source_sets/_source_list.html.erb, app/views/sources/_source_tile.html.erb, app/views/sources/show.html.erb, config/initializers/assets.rb, spec/models/source_spec.rb
This introduces a carousel on the `source#show` view that links to other sources from the same set.
The carousel is created using the [slick](https://github.com/kenwheeler/slick) JavaScript library.  The carousel is responsive, displaying a different number of sources depending on screen size.
The `source` model has an instance method, `related_sources`, that returns all of the _other_ sources from this source's associated set.  The `source` model also has a default sort order (before, the sort order was defined in the view, which could lead to inconsistencies in the application).
A new partial, `_source_tile.html.erb`, contains the HTML representation of a source "tile" (a stylized thumbnail and title link to the source), used on both the `source#show` and `source#index` pages.  Some …
=> carousel showing more sources on source#show view

app/controllers/source_sets_controller.rb, app/models/source_set.rb, app/views/source_sets/index.html.erb, spec/models/source_set_spec.rb, spec/views/source_sets/index.html.erb_spec.rb
This does a small refactor on two methods in the `source_set` model.  It removes redundant `self` statements and renames them to be more true to rails conventions.  I have tested this in my browser.
=> rename publish methods and remove un-needed self statement

app/assets/javascripts/form.js, app/assets/stylesheets/primary_source_sets.css, app/views/authors/_form.html.erb, app/views/guides/_form.html.erb, app/views/guides/edit.html.erb, app/views/guides/new.html.erb, app/views/source_sets/_form.html.erb, app/views/source_sets/edit.html.erb, app/views/source_sets/new.html.erb, app/views/sources/_form.html.erb, app/views/tags/_form.html.erb, app/views/tags/edit.html.erb, app/views/tags/new.html.erb, app/views/vocabularies/_form.html.erb, app/views/vocabularies/edit.html.erb, app/views/vocabularies/new.html.erb
On the admin new/edit forms for source_sets, sources, guides, tags, and vocabularies, there are checkbox menus that allow admins to assert relationships with other objects (ie. the vocabularies form has a checkbox menu of all tags, so that admins can check which ones should belong to the vocabulary).  These checkbox menus can be long and unwieldy, making the user experience quite unpleasant. 
This PR introduces links to show/hide the checkbox menus.  It also provides the user with a message if there are no associated objects to choose from.
This PR also deletes some unnecessary <br/> tags on the forms that to tighten up whitespace and make it easier to understand which labels are associated with which input boxes.
The UI experience has been tested locally and on staging.
This addresses …
=> expansible checkbox menus on admin form

app/views/source_sets/index.html.erb
This corrects a mistake in the `source_set#index` view.  The mistake occurred with a filter tag was included in the URL and the browser's JavaScript was disabled.  Before the, "Re-sort" continued to be visible even though the drop-down menu was hidden (see screenshot below).  This was confusing, and inconsistent with parallel behavior when JavaScript is enabled.  Now, the "Re-sort" button only shows if the dropdown menu is also visible.
I tested this in my local browser and it is working as expected.
This addresses [task 8286](https://issues.dp.la/issues/8286).
=> hide resort button when filter selected

spec/helpers/source_sets_helper_spec.rb
This fixes a helper test that was previously failing.  The helper method itself worked fine, the test was just incorrectly written.
This addresses [task #8244](https://issues.dp.la/issues/8244).
=> fix helper test

app/assets/stylesheets/primary_source_sets.css
This replaces two css closing brackets that were accidentally deleted when resolving merge conflicts.
This addresses [ticket #8317](https://issues.dp.la/issues/8317).
=> replace css closing brackets

app/assets/javascripts/carousel.js, app/assets/stylesheets/primary_source_sets.css, app/models/source_set.rb, app/views/source_sets/_set_list.html.erb, app/views/source_sets/_set_tile.html.erb, app/views/source_sets/show.html.erb, spec/models/source_set_spec.rb
This adds a carousel on the `source_set#show` view showing related sets.  The purpose of this feature is to encourage users to explore sets similar to one they are already looking at.  Its implementation is similar to the source carousel in [PR#112](https://github.com/dpla/primary-source-sets/pull/112).
Changes include:
* In the `SourceSet` model, a new method gets related sets, which are defined as sets sharing at least two tags.
* A new partial, `_set_tile.html.erb`, contains the HTML representation of a set "tile" (a stylized image and title link to the set), used on both the `source_set#show` and `source_set#index` pages. Some tweaks to the existing views and CSS ensure that it is usable in both places.
* Changes to the JavaScript ensure that the responsive design works with both the …
=> carousel showing related sets

app/models/source_set.rb, db/migrate/20160304170216_add_published_at_to_source_sets.rb, db/migrate/20160304170852_set_published_at_values.rb, db/schema.rb, spec/models/source_set_spec.rb
This replaces the ability to sort sets by their created date with the ability to sort sets by their published date.  This will make management of sets easier for admins.
* A `datetime` column, `published_at`, is added to the `source_sets` table.
* The value for the `published_at` column is set to the current value of the `created_at` column _if sets are already published_.  This will preserve the current sort order in production.  We do not currently have rspec tests for migrations (maybe something to look into for the future), but I tested this locally to ensure that it works as expected.
* A new `before_save` method is added to the `SourceSet` model to handle persistence of the publication timestamp.  If the set is being published upon save, the publication timestamp is set to the …
=> order sets by published date

Gemfile, app/assets/javascripts/poster.js, app/assets/stylesheets/application.css, app/assets/stylesheets/poster.css, app/controllers/posters_controller.rb, app/views/posters/index.html.erb, app/views/posters/show.html.erb, app/views/shared/_admin_menu.html.erb, config/initializers/assets.rb, config/routes.rb, spec/controllers/posters_controller_spec.rb, spec/views/posters/index.html.erb_spec.rb, spec/views/posters/show.html.erb_spec.rb
This introduces a new feature, "posters", which are static image representations of sets and guides to be used for marketing.  Static images include names of sets or guides, their associated images, and the DPLA logo.  Specifically, these images will be used when submitting sets and guides to PBS learning media.  Admins will screenshot the images for local use.  While this is admittedly not ideal, we are saving time by not trying to implement HTML to image file functionality.
There are new routes, controllers, and views, but no new models as all the data needed to construct the posters are in `SourceSet` and `Guide`.  JavaScript is used for dynamic styling.  Posters are only visible to admins.
A sample poster:
=> posters for sets & guides

app/assets/stylesheets/primary_source_sets.css, app/helpers/sources_helper.rb, app/models/source.rb, app/views/shared/_search_panel.html.erb, app/views/sources/show.html.erb, spec/helpers/source_helper_spec.rb, spec/models/source_spec.rb
This introduces a back link on the `source#show` page.  If the user come to a `source#show` page from a set or guide, the back link directs them back to the set or guide.  
We expect that users looking through a set or reading through a guide will need to do a lot of clicking back and forth between the set or guide and the sources contained within them.  The back links should facilitate this type of user experience. The back links are also operationally and stylistically akin to those on DPLA item pages.
I had initially considered including `back_uri`as a parameter of the `source#show` URL, a la:
http://dp.la/item/eed4628bb2544f92665632e85d350963?back_uri=http%3A%2F%2Fdp.la%2Fsearch%3Futf8%3D%25E2%259C%2593%26q%3Dhamster
However, links _to_ `source#show` _from_ guides (and possibly sets) …
=> back link and link to guide on source#show

app/models/tag.rb, app/views/tags/_form.html.erb, app/views/tags/index.html.erb, app/views/vocabularies/index.html.erb, spec/models/tag_spec.rb
This adds helpful text to `tag` and `vocab` forms explaining what tags, vocabularies, and tag URIs are.  It also changes the expected data type for the form form `text` to `uri`.  This will perform a build-in validation to make sure the the user-submitted data is a properly-structured URI.  If the user does not enter a URI, the interface shows a tooltip saying they need to enter a URI (screenshot below).
This addresses [ticket #8229](https://issues.dp.la/issues/8229).
=> Add URI validation and helper text to tag & vocab forms

Gemfile, app/controllers/concerns/api_queryer.rb, app/controllers/sources_controller.rb, app/views/sources/show.html.erb, config/initializers/dplibrary.rb, config/settings.yml, spec/controllers/concerns/api_queryer_spec.rb, spec/controllers/sources_controller_spec.rb, spec/views/sources/show.html.erb_spec.rb
This addresses https://issues.dp.la/issues/8098, adding a link to the provider's digital resource on the source page.
I didn't add any tests, because the real work is handled by DPLibrary, which has -- or should have -- its own tests. Let me know if you think the `logger.error` call in `ApiQueryer` should be tested.
Is it best to have the API functionality in a concern?  I think it probably is, but want to make sure that sits well with you.
I have `ApiQueryer#dpla_items` taking variable arguments, because originally I thought it would be like a model's `find` method, which does just that.  I'm not so sure now, though. Let me know if you think it would be best simply taking an array. I don't really know the circumstances under which we'll be querying multiple item IDs some day.
=> Add link to provider's digital resource.

Gemfile, app/assets/javascripts/application.js, app/assets/javascripts/poster.js, app/assets/javascripts/sequence.js, app/assets/stylesheets/application.css, app/assets/stylesheets/primary_source_sets.css, app/controllers/sequences_controller.rb, app/models/sequence.rb, app/models/tag.rb, app/models/vocabulary.rb, app/policies/access_policy.rb, app/views/vocabularies/edit.html.erb, app/views/vocabularies/index.html.erb, app/views/vocabularies/show.html.erb, config/initializers/assets.rb, config/routes.rb, db/migrate/20160310164755_rename_tags_vocabularies.rb, db/migrate/20160314132414_add_position_to_sequences.rb, db/migrate/20160314132424_set_position_values.rb, db/schema.rb, spec/controllers/sequences_controller_spec.rb, spec/factories/sequence.rb, spec/models/sequence_spec.rb, spec/models/tag_spec.rb, spec/models/vocabulary_spec.rb
This allows admins to order tags within vocabularies.  This is important for vocabularies such as "time period", where admins will want tags to display to users in chronological order.  Currently, tags are ordered by their created date, so admins have to consciously create tags in the order in which they want them to display. 
Tags and vocabularies have a many-to-many relationship.  This changes the name of their join table from `tags_vocabularies` to `sequences` for clarity.  A new field, `position`, has been added to the `sequences` table to record the sequential order in which tags should appear within vocabularies.  A final migration sets a `position` value for all existing rows in the join table.
A new model, `Sequence` has methods that check/amend `position` values when a sequence …
=> Allow admins to order tags within vocabularies

app/controllers/sources_controller.rb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb, spec/controllers/sources_controller_spec.rb
This changes the `<h2>` text for related set and sources for clarity.
It also sets a `@source_set` variable for `source#show` - I noticed there were several calls to `@source.source_set`, and wanted to reduce calls to the database.
This addresses [ticket #8323](https://issues.dp.la/issues/8323).
=> change header text for related sets and sources

app/assets/stylesheets/primary_source_sets.css, app/controllers/registrations_controller.rb, app/views/registrations/edit.html.erb, app/views/registrations/index.html.erb, app/views/registrations/new.html.erb, db/migrate/20160317140404_add_username_to_admins.rb, db/schema.rb, spec/controllers/registrations_controller_spec.rb, spec/factories/admins.rb, spec/views/registrations/edit.html.erb_spec.rb, spec/views/registrations/index.html.erb_spec.rb, spec/views/registrations/new.html.erb_spec.rb
This adds a `username` field to admins.  This will help managers to identify other admins who may not have easily identifiable email addresses.  `username` is not a required field.
In summary:
- A `username` field is added to the `admins` table.
- `username` is included as a permitted param for `new` and `update` controller methods.
- `username` is added to `index`, `new`, and `edit` views.
- Controller tests (with associated factories) make sure that `username` can be created and edited.
- View specs for `index`, `new`, and `edit` are added.
- A little CSS styling makes it look nice.
This addresses [#8264](https://issues.dp.la/issues/8264).  It has been tested locally.
=> Add admin username

app/models/source.rb, spec/models/source_spec.rb
This adds a validation to the `Source` model ensuring that the value for an aggregation (ie. the ID of an item in DPLA) is comprised of letters and numbers.  This will help to prevent errors elsewhere in the system, where links are formed to items in the frontend using the aggregation (ie.  http://dp.la/item/90aade1f9d91965c921026d3b0dc2d8f). 
This addresses [ticket #8330](https://issues.dp.la/issues/8330).
=> validate that aggregation is only letters and numbers

app/views/audios/new.html.erb, app/views/documents/new.html.erb, app/views/guides/edit.html.erb, app/views/guides/new.html.erb, app/views/images/new.html.erb, app/views/layouts/application.html.erb, app/views/posters/show.html.erb, app/views/source_sets/edit.html.erb, app/views/source_sets/new.html.erb, app/views/source_sets/show.html.erb, app/views/sources/_image.html.erb, app/views/sources/edit.html.erb, app/views/sources/new.html.erb, app/views/sources/show.html.erb, app/views/tags/edit.html.erb, app/views/tags/new.html.erb, app/views/videos/new.html.erb, app/views/vocabularies/edit.html.erb, app/views/vocabularies/new.html.erb
This moves all included javascript files to the HTML `<head>` and uses the `defer` tag to ensure that the javascripts do not load until after the page has finished parsing.  Before, we were inconsistently using the `defer` tag and putting included javascript files in both the `<head>` and after the `<body>`.
The `defer` attribute is supported by all major browsers of reasonably recent versions: http://www.w3schools.com/tags/att_script_defer.asp
This has been tested in a local deployment, but since we do not have full tests for all javascript functionality, it should be deployed and manually tested by a second set of eyes.
This addresses [ticket #8248](https://issues.dp.la/issues/8248).
=> move javascript to head with defer attribute

app/assets/javascripts/social.js, app/assets/stylesheets/primary_source_sets.css, app/views/guides/show.html.erb, app/views/shared/_share.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb, config/initializers/assets.rb
This adds social media share buttons to sets, sources, and guides (show views only).  The HTML and javascript are copied exactly from the frontend application for consistency and ease of maintenance.  A small amount of CSS improves the display.
This addresses [ticket #7922](https://issues.dp.la/issues/7922).
=> social media share buttons

app/controllers/authors_controller.rb, app/views/authors/_form.html.erb, app/views/authors/edit.html.erb, app/views/authors/new.html.erb, app/views/guides/show.html.erb, app/views/source_sets/show.html.erb, spec/controllers/authors_controller_spec.rb
This adds checkbox menus to the forms to create and edit authors. The menus allow admins to associate authors with existing sets or guides. Similar checkbox menus already appear on create/edit forms for sets, guides, sources, vocabularies, and tags.  Existing JavaScript code is included - this JavaScript allows end users to expand and collapse menus for easy readability.
This also allows you to specify a set or guide to be associated with the author in the URL for the new author form.  So, for example, `/authors/new?guide_id=1` will pre-populate the guides menu so that the guide with id=1 is checked.  This will help admin workflow.  A similar feature already exists for tags and vocabularies.
This addresses [ticket #8297](https://issues.dp.la/issues/8297).
=> add guide and set menus to authors form

app/assets/stylesheets/primary_source_sets.css
This adds padding to tables for legibility.  Many admin views contain HTML tables. These tables currently have no padding or margins, making them difficult to read.  HTML tables are not used in any other capacity in the application.
Before spacing was added:
After spacing was added:
This addresses [ticket #8353](https://issues.dp.la/issues/8353).
=> add spacing to tables

app/assets/javascripts/form.js, app/views/authors/_form.html.erb, app/views/authors/show.html.erb, app/views/guides/_form.html.erb, app/views/guides/show.html.erb, app/views/source_sets/_form.html.erb, app/views/source_sets/show.html.erb, app/views/sources/_form.html.erb, app/views/sources/show.html.erb, app/views/tags/_form.html.erb, app/views/tags/show.html.erb, app/views/vocabularies/_form.html.erb, app/views/vocabularies/show.html.erb
This improves the ways that admins can manage associations between objects using forms.
Before this PR, there were links on various #show views that allowed users to create _new_, associated objects.  For example, on the `/sets/123` view, there was a link that said "Add new tag", which linked to `/tags/new?source_set_id=123`.  The new tags form would be pre-populated with the set id to assert the association.  
Admins could also build associations between _existing_ objects on various #new and #edit forms.  For example, on `sets/123/edit`, there was a menu of existing tags that an admin could select in order to associate them with the set.
This was confusing for admins because they needed to go to separate views to do related tasks, ie. associating tags with a given set.
This improves the …
=> Improve workflow links for building associations between objects.

app/assets/stylesheets/primary_source_sets.css
This fixes the style of the `<h1>` element on `/source/show`.  Before this fix, the new social media share button was causing it to float in an odd and unattractive way:
Now, it floats in a lovely and sensible way:
This addresses [ticket #8357](https://issues.dp.la/issues/8357).
=> fix header layout on source page

app/views/shared/_top_nav.html.erb
Change the "Curation Corps" link in the navbar to "Ebooks".  This addresses [ticket #8358](https://issues.dp.la/issues/8358).
=> Update ebooks link in nav bar

app/models/source_set.rb, spec/models/source_set_spec.rb
This fixes the `related_sets` method of the SourceSet model to only return published sets, as opposed to both published and unpublished sets.  The `related_sets` method is used to populate the "Related sets" carousel on the `sets/show` view.  Since unpublished sets are not accessible to the public, they should not be included in the slider.
This is a high-priority fix as it is currently holding up data entry for the final content release.
This has been tested locally.  It addresses [ticket #8362](https://issues.dp.la/issues/8362).
=> only show published sets in related sets slider

app/assets/stylesheets/primary_source_sets.css, app/views/sources/show.html.erb
This changes the static HTML text on `/source/show` and the accompanying CSS.  This addresses [ticket #8356](https://issues.dp.la/issues/8356).
=> change static text in sidebar

app/controllers/sources_controller.rb, app/views/sources/_hub_analytics.html.erb, app/views/sources/show.html.erb
This uses Google Analytics to track use of hubs' items.
When a `/source/show` page is loaded in a browser window, a message is sent to Google Analytics with the DPLA item ID, provider name, contributing institution, and title.  It matches the message sent to Google Analytics when an item is viewed in the DPLA portal.
Testing on staging, the message sent to Google Analytics is:
If you want to test yourself on staging you can use the [Google analytics debugger Chrome plugin](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en).
This addresses [ticket #8065](https://issues.dp.la/issues/8065).
=> track use of items for hubs

app/views/source_sets/index.html.erb
This adds a social media share button to the sets index view.  It addresses [ticket #8363](https://issues.dp.la/issues/8363).
=> add social media button to set index view

app/views/audios/show.html.erb, app/views/authors/show.html.erb, app/views/documents/show.html.erb, app/views/guides/show.html.erb, app/views/images/show.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb, app/views/tags/show.html.erb, app/views/videos/show.html.erb, app/views/vocabularies/show.html.erb
This adds links to create new objects on their `show` views.  Links are only visible to logged-in admins.  This will help streamline data entry.  It addresses [ticket #8364](https://issues.dp.la/issues/8364).
=> add links to new objects in show views for admins

Gemfile
Now that some necessary changes have been accepted and merged, use the DPLibrary repository instead of our fork of it.
=> Change location of DPLibrary gem

app/views/sources/_document.html.erb
This fixes the Google document viewer to work with HTTPS.
=> add https to doc viewer link

spec/helpers/source_helper_spec.rb
This fixes a test that was failing for me locally.  In a helper test, it uses the value from `Settings.app_scheme` instead of a hardcoded `http://` to construct a URL.  This is related to the switch to SSL.
=> Use Settings.app_scheme instead of hardcoded protocol in helper test

app/views/sources/show.html.erb
This renders the name of a guide in markdown on the source show view.  Some guides have markdown elements, such as italics for book titles.  
This has been tested locally.  It addresses [ticket #8365](https://issues.dp.la/issues/8365).
=> render guide markdown on source show view

Gemfile
This locks the `phantomjs` version to 1.9.8.  This will hopefully solve the problem of failing CI builds.  This addresses [ticket #8367](https://issues.dp.la/issues/8367).
=> lock phantomjs to v1.9.8

app/assets/stylesheets/primary_source_sets.css, app/views/sources/show.html.erb
If a user does not have JavaScript enabled in their browser, they cannot load media assets. Audio and video files will not play; images will not load; and the document viewer does not load interactive features, such as scroll and zoom.  Instead of trying and failing to render the media objects, this displays an error message to users explaining that they need JavaScript. 
The `div` containing the media object is given the class `js-off`, which by default does not display.  A JavaScript function displays all objects with this class when the page loads.  See https://github.com/dpla/primary-source-sets/blob/develop/app/assets/javascripts/style.js#L10
The rendered message looks like this:
=> add error message if javascript disabled

spec/controllers/sources_controller_spec.rb
This addresses a "FIXME" note that was left in a controller spec.  Apparently a previous iteration of the code base prevented it from running a shared example test.  Now, it runs just fine.  The instance variable mentioned in the comment, `@file_base_or_name`, is by default set to `nil` in the controller `:show` method, which seems to eliminate the need for a mock.
=> allow basic controller tests to run

app/helpers/application_helper.rb, app/views/guides/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_share.html.erb, app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb, spec/helpers/application_helper_spec.rb
This adds custom language for an auto-generate tweet, which includes the page URL, page title and "@dpla".  In order to easily include the page title in the tweet, page titles are now accessible with `content_for`.  The twitter account name, `dpla`, is already defined in the settings file through aws: https://github.com/dpla/aws/blob/0e10b825dbb3d66fb3930d583376ceddc5fda9a8/ansible/group_vars/production#L40
Now, for example, when you click on the Twitter share button from `/primary-source-sets/`, you are taken to a page where you see this:
This has been tested locally.  It addresses [ticket #8360](https://issues.dp.la/issues/8360).
=> custom language for auto-generated twitter post

app/views/guides/show.html.erb, app/views/source_sets/index.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb
This adds jumplinks to public-facing pages that improve accessibility of the website.  
Prior to this PR, there were jumplinks to HTML elements with `id='content'` in our accessibility menu (see https://github.com/dpla/primary-source-sets/blob/develop/app/views/shared/_jump_links.html.erb#L5).  However, we were not actually implementing these links.  This PR adds HTML elements with `id='content'` to all public-facing pages.
Now, for example, you could use the following link to access the main content of the page:  `/primary-source-sets#content`
This has been tested locally.  It addresses [ticket #8385](https://issues.dp.la/issues/8385).
=> add content jumplinks

app/assets/javascripts/style.js, app/assets/stylesheets/primary_source_sets.css, app/views/source_sets/show.html.erb, app/views/sources/_audio.html.erb, app/views/sources/_document.html.erb, app/views/sources/_image.html.erb, app/views/sources/_video.html.erb, app/views/sources/show.html.erb
fix/css-dimensional-manipulation
This uses CSS instead of JavaScript for most dimensional manipulation.  This will improve user experience for people with JavaScript disabled in their browsers.  The changes in this PR also improves UX overall by making the views slightly more responsive for all browsers.
Before, JavaScript was used to ensure that certain boxes on a page were the same height within a responsive design.  This instead uses the CSS3 flexbox feature.
There is one dimensional manipulation that is still handled with JavaScript, but I think it is outside the scope of this PR because 1) the solution would be complex and therefore time consuming, 2) it requires a different kind of solution than the one employed in this PR, and 3) the degradation of UX for those without JavaScript …
=> css for dimensional manipulations source, source and set show views

spec/helpers/application_helper_spec.rb
This addresses a "TODO" in the application helper spec.  It adds a shared context that allows the spec to test the output of two methods both when the frontend assets gem is defined, and when it is not defined.  Before, it was only testing with the assumption that the gem was defined.
This addresses [ticket #8140](https://issues.dp.la/issues/8140).
=> add test contexts with and without frontend assets gem

app/views/layouts/application.html.erb
This fixes a bug introduced in [PR#157](https://github.com/dpla/primary-source-sets/pull/157).  I deleted the code that included the Twitter widgets JavaScript library, and forgot to add it back in again.  Without this library, the twitter button renders as a simple link, as opposed to a stylized button.
=> add twitter widget js

app/controllers/guides_controller.rb, app/controllers/source_sets_controller.rb, app/controllers/sources_controller.rb, app/helpers/application_helper.rb, app/helpers/audio_player_helper.rb, app/helpers/markdown_helper.rb, app/helpers/video_player_helper.rb, app/views/guides/_show.json.erb, app/views/shared/_context.json.erb, app/views/source_sets/_show.json.erb, app/views/sources/_show.json.erb, config/settings.yml, etc/PrimarySourceSetDataModelSample.json, spec/controllers/guides_controller_spec.rb, spec/controllers/source_sets_controller_spec.rb, spec/controllers/sources_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/helpers/markdown_helper_spec.rb, spec/support/shared_examples/valid_json_view.rb, spec/views/guides/_show.json.erb_spec.rb, spec/views/source_sets/_show.json.erb_spec.rb, spec/views/sources/_show.json.erb_spec.rb
This adds the option to get sets, sources, or guides in JSON-LD format, according to our data model for this project.
Changes include:
* Updates to the sample data model in `etc/PrimarySourceSetDataModelSample.json` to reflect available metadata and correct object structure.
* Controllers respond to requests for `json` format.  For code simplicity, a few instance variables are added to the controllers.  It is outside the scope of this PR to refactor `html` views to use these new instance variables, but that work is slotted in another upcoming ticket.
* `.json` view templates are added.
* A few helpers are refactored so that they will work with both `html` and `json` views.
* Specs for controllers, views, and helpers are added/updated.  A few methods are moved out of the …
=> JSON-LD show views for set, guide, and source

app/views/guides/show.html.erb, app/views/source_sets/show.html.erb, app/views/sources/show.html.erb
This embeds the JSON-LD markup for sets, guides, and sources within the HTML.  It is intended to boost SEO.  The JSON-LD partials already exist.
This addresses [#8187](https://issues.dp.la/issues/8187).
=> embed json-ld in html pages

Gemfile, config/environments/development.rb, config/environments/production.rb, config/initializers/session_store.rb, config/settings.yml, provisioning/provision.yml
* Add the ability to use the rails `cache_store` session handler.
* Set up the Rails `cache_store`.
* Add the `dali` gem to support memcached.
Is this a good way to set up the Rails cache_store, for other use in addition to sessions?
Is there some better way to set `config.cache_store` that doesn't duplicate code between `development.rb` and `production.rb`? I wasn't able to make it work by creating my own initializer.
The `memcached` package is added to the VM, so you can run `vagrant provision` on it and it will be started. You can then update your `settings.local.yml` with a host `localhost` if you want to use memcached. For example:
```
cache:
store: mem_cache_store
opts:
- localhost
```
=> Add support for cache_store sessions

app/helpers/source_sets_helper.rb, spec/helpers/source_sets_helper_spec.rb
This fixes a bug introduced in PR#165.  On source_sets#index, the tags listed in the dropdown menu were out of order.  They are supposed to be ordered according to the "position" field in the "tag_sequences" table.  This PR fixes the dropdown menus this so that the positions defined in the tag_sequences table are enforced.
This has been tested locally and is working as expected.  It addresses [ticket #8424](https://issues.dp.la/issues/8424).
=> order filters_for_sets by tag_sequences.position

app/helpers/source_sets_helper.rb
This fixes a bug introduced in [PR#169](https://github.com/dpla/primary-source-sets/pull/169/files).  #169 was tested and worked locally (sqlite database), but failed when deployed to staging (postgresql database).  Postgresql requires that any columns in a ORDER BY clause also appear in a SELECT clause.
This has been tested on staging.  It addresses [ticket #8242](https://issues.dp.la/issues/8424).
=> fix order by db call for postgresql

Gemfile
This pins the DPLibrary gem to a release version, rather than pulling from the master branch.
=> pin DPLibrary gem to v0.1

Gemfile
Pin all gems to the tiny version that are currently deployed to production.
=> pin all gems to tiny versions

app/views/shared/_top_nav.html.erb
Change the DPLAfest link in the main menu.  This addresses [ticket #8552](https://issues.dp.la/issues/8552).
=> change dplafest main menu link

config/application.rb, config/settings.yml
This allows us to set X-Frame-Options for primary source sets.  Along with accompanying changes to [automation](https://github.com/dpla/automation/pull/205) and [aws](https://github.com/dpla/aws/pull/47), it will allow OER commons to display an iframe of primary source sets.  OER commons indexes our sets in their educational resources discovery tool.
I have run a local deployment with the aws and automation changes, and verified with curl:
This addresses [ticket #8490](https://issues.dp.la/issues/8490).
=> configure x-frame-options

app/assets/stylesheets/application.css, app/assets/stylesheets/av_download.css
This uses a CSS hack to hide download buttons on audio and video elements in Chrome.
This has been deployed to staging for testing.  I have tested it on all my available browsers and devices, as well as the Chrome viewport controls.  Further testing would be appreciated!  We need to ensure not only that the download button is hidden on Chrome, but also that no other controls are accidentally hidden on other browsers.
You can use these examples on staging:
Audio example: https://staging.dp.la/primary-source-sets/sources/5
Video example: https://staging.dp.la/primary-source-sets/sources/6
And compare with these examples on production:
Audio example: https://dp.la/primary-source-sets/sources/1211
Video example: https://dp.la/primary-source-sets/sources/1208
This addresses [ticket …
=> hide av download button on chrome with css

app/views/layouts/application.html.erb
This adds a meta referrer tag to the head of each page.  This will allow external sites not using HTTPS to track traffic from DPLA.  It has been tested on staging.  This addresses ticket [DT-1201](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1201).
=> add meta referrer tag

app/views/shared/_top_nav.html.erb
This removes the "Events" link from the "Get Involved" menu.  It has been tested on staging.  It addresses [DT-1195](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1195).
=> remove events from menu

app/controllers/source_sets_controller.rb, app/views/source_sets/_index.json.erb, spec/controllers/source_sets_controller_spec.rb, spec/views/source_sets/_index.json.erb_spec.rb
This adds a JSON view for the `sets#index` page.  It lists the URIs of all the sets, which will allow us to harvest sets via HTTP.  It also lists the name and schema.org type for each set, which follows precedent set elsewhere in the app (ie. https://github.com/dpla/primary-source-sets/blob/develop/app/views/source_sets/_show.json.erb#L57:L80).
This is the first step to addressing [ticket DT-1393](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1393).  It has been tested locally and on staging.  It is currently deployed to staging, in case anyone wants to use it to test the primary source sets harvester.
The second step to addressing ticket DT-1393 is [ingestion3#17](https://github.com/dpla/ingestion3/pull/17).
=> add json view for sets#index

config/environments/production.rb
This adds SSL configurations for the `Devise` gem, which manages user accounts.  It restores the browser feature that allows current users to create new user accounts.  This feature was broken before.
This has been tested on staging.  It addresses [ticket DT-1319](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1319).
=> Add SSL settings for the Devise gem

app/views/source_sets/_index.json.erb
This adds tag lists to the JSON API.  It is to help Postlight make Subject and Time Period dropdown menus on the landing page.  This addresses [ticket DT-1550](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1550).
=> add tags to json api

app/controllers/concerns/encoder.rb
Fix error encountered in logging an exception's message in `Encoder#create_media`. The variable `model` is an ActiveRecord model, not a string, and does not have a `#capitalize` method. `type.to_s` does, and gets more to the point, anyway.
=> Fix error logging exception message

app/models/dpla_item.rb
This handles an array of provider URLs coming through the DPLA API.  Currently, Digital Maine's provider URLs are in array format.  This has been tested on staging.
=> handle array of provider URLs

app/views/sources/_document.html.erb
In document view, do not add 'https://' to the beginning of the PDF URL, because `#base_src` already adds the scheme.
=> Fix Google Docs Viewer URL generation

app/helpers/application_helper.rb, app/views/source_sets/_index.json.erb, app/views/source_sets/_show.json.erb, app/views/sources/_show.json.erb
Add "repImageUrl" properties alongside existing "thumbnailUrl" properties in the API.  These new properties are file names that are the same as the thumbnail images, except that they have "_thumb" or "_sm" torn off, if they are present, and the basename ends with "_rep".
See https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1615
I've solicited feedback from Postlight about this, but maybe in the meantime this can be reviewed so it's ready to go if they think it's OK.
=> Kludge in "rep" thumbnail images for Postlight frontend

app/views/sources/_show.json.erb
This adds citations and the provider name to the source JSON for the PSS API.  This will unblock the following Trello tickets, which relate to the new frontend rollout:
https://trello.com/c/xAYaWGcn/76-instead-of-item-source-and-dpla-record-the-links-should-be-view-on-provider-and-view-in-dpla
https://trello.com/c/OpBS2LoS/19-source-pages-for-primary-source-sets-are-missing-courtesy-statements
This PR addresses [DT-1647](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1647).  It has been tested locally.
=> add citation and provider to source json

Gemfile.lock
This restores two lines from `Gemfile.lock` that accidentally got into my git history and committed with the last PR.
=> restore BUNDLED WITH

config/application.rb
This fixes syntax to align with a change in Bundler 1.6 (see https://github.com/bundler/bundler/commit/8ccf49c3b4a086f1e0cad2130dc30c04304175b7#diff-75219bd6bc0defc0e7f4ba322d92f950L198).  This fixes deployment to staging, which was failing.
=> change bundler without syntax

.travis.yml
This disables Jasmine in the Travis test suite.  It is intended as a temporary measure until we can fix Jasmine (see [DT-1832](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1832)).  In the meantime, it allows us to see clearly if the other Travis tests are passing or failing.
=> turn off jasmine in travis test

app/views/sources/_show.json.erb
This fixes a logic flow problem in the JSON representation of a source.  Before, the `citation` was only included if the item ID was valid.  Now, the `citation` is included regardless.  This has been tested locally.  It addresses https://github.com/dpla/dpla-frontend/issues/721
=> fix log flow of source json

app/models/dpla_item.rb
This catches `StandardError` when attempting to fetch items from the DPLA API.  `StandardError` is quite broad, so we're playing it very safe here.  We could just catch `Faraday::Error::ParsingError` which works for the specific problem of an item ID not being found in the DPLA index.  However, it occurs to me that there could be other errors bubbling up here as well, like network errors.  And I imagine that no matter what the error, we would just want to log it and return something benign that won't cause the webpage to crash.  So I opted for `StandardError` but please let me know if you don't agree.
This has been tested locally.  It addresses https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-2197
=> catch standarderror when fetching items from DPLA API
