etc/PrimarySourceSetDataModelSample.json, etc/TeachingGuideDataModelSample.json
This simplifies the data model and brings it into alignment with the relational database.
=> update json samples

.gitignore, Gemfile, app/assets/stylesheets/application.css, config.ru, config/environments/production.rb, config/initializers/config.rb, config/initializers/mount_location.rb, config/settings.local.yml.example, config/settings.yml
This appends `primary-source-sets/` to routes.  It also introduces `config` gem to manage settings.
=> append primary-source-sets/ to routes

.gitignore, spec/spec_helper.rb
=> Enable test coverage with simplecov

app/views/source_sets/show.html.erb, app/views/sources/show.html.erb, config/settings.yml
This adds a contact link to the `sources#show` view.
=> add contact link to source#show

app/assets/stylesheets/primary_source_sets.css, app/views/guides/show.html.erb
This introduces CSS styling for a guide.
=> style teaching guide

app/views/source_sets/_source_list.html.erb
This sorts sources by date created on the `source_set#show` view.
=> sort sources by date created

app/assets/stylesheets/primary_source_sets.css, app/views/source_sets/index.html.erb
This styles `source_sets#index`.
=> style source_sets#index

app/views/shared/_top_nav.html.erb
Add education tab to top-level menu.
=> add education menu

README.md
Add instructions for running rspec and jasmine tests to `README.md`.
=> update README with testing instructions

app/views/layouts/application.html.erb
Remove these from stylesheet `<link>` elements.
=> Remove obsolete data-turbolinks-track attributes

app/views/source_sets/index.html.erb
This changes the static text on `/sets/index`.  It addresses [ticket #8343](https://issues.dp.la/issues/8343).
=> edit landing page static text

app/views/source_sets/index.html.erb
This fixes the social share button on the set index page to include the necessary JavaScript.
=> add javascript file

app/views/source_sets/show.html.erb, app/views/sources/show.html.erb
Load external JavaScript slick files with https
=> load js slick files with ssl

app/views/shared/_footer_nav.html.erb
This fixes the link to the apps page in the footer so it has the correct URL.  This has been tested locally.  It addresses [ticket #8384](https://issues.dp.la/issues/8384).
=> fix link to apps

app/views/shared/_top_nav.html.erb
Add link in main nav to tech team wiki.
This addresses [ticket #8487](https://issues.dp.la/issues/8487).
=> add link to tech wiki in main nav

app/views/shared/_top_nav.html.erb
Add top-level menu link to "Searching DPLA" page.
This addresses [ticket #4683](https://issues.dp.la/issues/4683).
=> add menu link to Searching DPLA

app/views/shared/_top_nav.html.erb
This addresses [ticket #8531](https://issues.dp.la/issues/8531).
=> change gif it up link in main menu

app/views/source_sets/index.html.erb
This changes the intro text, adding a new link.  It has been deployed to staging for review: https://staging.dp.la/primary-source-sets/
This addresses ticket [DT-1186](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1186).
=> edit intro text

app/views/shared/_top_nav.html.erb
This has been tested locally.  It addresses [ticket DT-1253](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1253).
=> add family research link to main menu

app/controllers/source_sets_controller.rb, app/controllers/sources_controller.rb, app/views/guides/_show.json.erb, app/views/source_sets/_index.json.erb, app/views/source_sets/_show.json.erb, app/views/source_sets/show.html.erb, app/views/sources/_show.json.erb, app/views/sources/show.html.erb, config/application.rb, spec/controllers/source_sets_controller_spec.rb, spec/views/source_sets/_show.json.erb_spec.rb
This adds fields to the JSON-LD for Postlight.  It also adds CORS settings that will allow them better read-access to the API.  This has been tested on staging.  It addresses [DT-1522](https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1522).
=> Dt 1522 postlight api

Gemfile, Gemfile.lock, app/views/guides/_show.json.erb, app/views/source_sets/_index.json.erb, app/views/sources/_show.json.erb
This adds more HTML safe fields to the JSON API.  It has been tested locally.
=> make more json fields html safe

app/views/sources/_show.json.erb
This adds two fields to the json API that are needed for Google Analytics events on the new frontend.
=> add contributor and item name to json feed
